### ISSUE TITLE
calling with Rscript gives an error

### ISSUE THREAD

**Issue by roryk** [COMBINE-lab/wasabi#1]
Hi everyone,

This unlikely has anything to do with `wasabi` specifically but maybe you can point me where to look. 

If I load R and run prepare_fish_for_sleuth it works fine:

``` r
> prepare_fish_for_sleuth(c("/v-data/bcbio-nextgen/tests/test_automated_output/sailfish/Test1/"))
Fri Dec 18 21:14:54 2015
[1] "Successfully converted sailfish / salmon results in /v-data/bcbio-nextgen/tests/test_automated_output/sailfish/Test1/ to kallisto HDF5 format"
[1] "/v-data/bcbio-nextgen/tests/test_automated_output/sailfish/Test1/"
>
```

But if I run it from Rscript, it doesn't: 

``` bash
rm /v-data/bcbio-nextgen/tests/test_automated_output/sailfish/Test1/abundance.h5
/usr/local/share/bcbio/anaconda/bin/Rscript -e 'library("wasabi"); prepare_fish_for_sleuth(c("/v-data/bcbio-nextgen/tests/test_automated_output/sailfish/Test1"))'
Error in H5Fcreate(file) : could not find function "new"
Calls: prepare_fish_for_sleuth ... sapply -> lapply -> FUN -> h5createFile -> H5Fcreate
Execution halted
```

Here is the sessionInfo():

``` r
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.1 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] wasabi_0.1

loaded via a namespace (and not attached):
[1] zlibbioc_1.16.0  rjson_0.2.15     rhdf5_2.14.0     data.table_1.9.6
[5] chron_2.3-47
```

Do you have any tips? We were hoping to include this as a step in `bcbio-nextgen` to have outputs that people can use for Sleuth ready to go.

**Comment by roryk** [comment]
I can get around this if I load `rhdf5` specifically in the Rscript call:

``` bash
/usr/local/share/bcbio/anaconda/bin/Rscript -e 'library("wasabi"); library("rhdf5"); sf=c("/v-data/bcbio-nextgen/tests/test_automated_output/sailfish/Test1"); prepare_fish_for_sleuth(sf)'
Loading required package: methods
Fri Dec 18 21:31:16 2015
[1] "Successfully converted sailfish / salmon results in /v-data/bcbio-nextgen/tests/test_automated_output/sailfish/Test1 to kallisto HDF5 format"
[1] "/v-data/bcbio-nextgen/tests/test_automated_output/sailfish/Test1"
```

**Comment by blahah** [comment]
It's a bug :). We should be using the full namespace for functions in `rhdf5` - the reason it works when you load via `library(rhdf5)` is that all those functions get attached to the global namespace.

Fix incoming.

**Comment by roryk** [comment]
Awesome, thanks for the explanation.

**Comment by roryk** [comment]
Thanks @Blahah, sorry to be a pain in the ass. Still have this issue, any ideas?

fix installed:

``` bash
git rev-parse HEAD
aaf544ae8c21feb03dbe875e496e0a4eed3ab2b6
/usr/local/share/bcbio/anaconda/bin/R CMD INSTALL .
```

``` bash
/usr/local/share/bcbio/anaconda/bin/Rscript -e 'library("wasabi"); sf=c("/v-data/bcbio-nextgen/tests/test_automated_output/sailfish/Test1"); prepare_fish_for_sleuth(sf)'
Error in H5Fcreate(file) : could not find function "new"
Calls: prepare_fish_for_sleuth ... sapply -> lapply -> FUN -> <Anonymous> -> H5Fcreate
Execution halted
```

**Comment by blahah** [comment]
Hmm, sorry about that. Investigating now

**Comment by blahah** [comment]
Oh - silly me. The problem is that RScript does not load the `methods` package by default! I've added it as a dependency explicitly - if you use the head now does it work?

**Comment by roryk** [comment]
Yup-- that totally works. Thanks!

**Comment by blahah** [comment]
Excellent :)

**Comment by rob-p** [comment]
Great!  Thank you guys for working this one out while I was in grading hell ;P.

**Comment by roryk** [comment]
Thanks for the fix, I added this and the new version of Sailfish to [bioconda](https://github.com/bioconda). I'm psyched that we can use `sleuth` now.

**Comment by rob-p** [comment]
Awesome!  It was actually possible to use sleuth with Sailfish and Salmon before via [@Blahah's fork of sleuth](https://github.com/Blahah/sleuth).  However, maintaining a separate fork of the whole package seemed a lot of work to accomplish something rather simple.  So, the main purpose of wasabi is to make a simple, stand-alone package for preparing the Sailfish and Salmon output so that one can just use the main branch of sleuth without any modifications.  Thanks for adding this stuff to bioconda!

**Comment by roryk** [comment]
Sweet, I had tried the fork when you all posted about it on your blog a couple of months ago but I couldn't get it to work. And then I saw the `sleuth` folks said the format might be in flux and closed your compatibility pull request so I thought I'd just wait until all of that settled down. Thanks for being super responsive maintainers, I know it is a lot of work and you don't get much professionally from it.

**Comment by rob-p** [comment]
Yea; this approach should make it much easier to just use the main version of sleuth, and should simplify maintaining compatibility if / when they modify the assumed input format.  I'm updating our blog post to use wasabi now, I'll ping here when I'm done.

**Comment by rob-p** [comment]
Done.  The changes are fairly minor and the updated blog post is [here](http://robpatro.com/blog/?p=291).  Hopefully this will work for you with no hiccups (should work with all the same versions of sf/salmon since the original blog post, but I highly recommend upgrading to sailfish v0.9.0 to test this out).
