### ISSUE TITLE
Shiny - 0 bootstraps 

### ISSUE THREAD

**Issue by rbenel** [COMBINE-lab/wasabi#11]
Hi @rob-p, 
It is nice to be talking to you about the next stage of the analysis :) 
So, I ran Salmon with 100 bootstraps (see attached file, a single log file from the Salmon run), and then used Wasabi to import my results into Seluth. Now when I use the Shiny app to visualize results, I have 0 bootstraps (see attached download_summary_table). Does this possibly have something to do with the Wasabi import? Because I did not run Kallisto?

Thanks!
Rina 

[salmon_quant.log](https://github.com/COMBINE-lab/wasabi/files/2087890/salmon_quant.log)
[download_summary_table.txt](https://github.com/COMBINE-lab/wasabi/files/2087895/download_summary_table.txt)

**Comment by rob-p** [comment]
Hi Rina,

  The salmon log looks totally fine.  Did you encounter any issues when running wasabi? Do you get the other information imported OK? Could you share the quants for 1 or 2 samples for me to try and reproduce this (wont have a chance until later)?  Also, wasabi basically creates an hdf5 object for each salmon quant dir.  Can you see these objects? Do they seem like they are created correctly?

Best,
Rob

**Comment by rbenel** [comment]
Hi @rob-p, 
I didn't encounter any specific issues when running wasabi. The other information seems to be imported correctly. I do see the abundance.h5 file within the quant.dir. When you say quants, do you mean only the quant.sf file or the entire directory created?

**Comment by rob-p** [comment]
I mean the entire directory.  Wasabi reads both the quant.sf and some other files in aux_info to generate the hdf5.  If you can share a pair of quant dirs I'd be happy to take a look this evening.  You could also try inspecting the hdf5 file to see if they look to contain the bootstraps.  The python or R library for reading hdf5 files would be most helpful with that.

--Rob

**Comment by rbenel** [comment]
Yes, I assumed Wasabi reads multiple files in order to create the abundance file. 
I will install the R package for reading hdf5 files, and inspect. 

The dir are larger than 10 MB when compressed, so here are two links to their dropbox folder:
sample_1:
https://www.dropbox.com/sh/p3qux5fnbtjmc07/AAAB04v09YBgyFnASSe4IW5ia?dl=0
sample_2:
https://www.dropbox.com/sh/nj3frweh6m3dp0v/AABK-JQGN41NJBZItg0IfBv7a?dl=0

Thank you so much for checking this out. 
Best, 
Rina

**Comment by rob-p** [comment]
Hi @rbenel,

  I seem to be able to load the bootstraps successfully using the samples you shared.  This is the image from the 2-sample data table in the shiny app after I load these samples:

![image](https://user-images.githubusercontent.com/361470/41206747-f40abf32-6cd6-11e8-9bbc-0da9ba62a4ff.png)

I'm not sure if its necessary, but one thing I did was to pass `extra_bootstrap_summary = TRUE` when calling `sleuth_prep` --- like so:

```
so <- sleuth_prep(s2c, extra_bootstrap_summary = TRUE)
```

Does this make a difference for you (if you weren't already doing it)?

--Rob

**Comment by rbenel** [comment]
Hi @rob-p,
I have already been passing the `extra_bootstrap_summary =TRUE` already into the sleuth_prep, so I don't think that is the issue here. 
Any other thoughts? 

Thanks for processing the files and working on this! 

Rina

**Comment by rob-p** [comment]
Sure --- Can you say what the commands were you used to import the data, and what the output of `sleuth_prep` was?  I basically created a simple (fake) 2 condition (1 sample per condition) experiment table, and directly loaded the data you shared via Dropbox.

**Comment by rbenel** [comment]
#import data by setting wd to dir where all the quants files are
`setwd(paste0(local_path,'......'))`
`sf_dirs <- dir()`	 

#####
`so <- sleuth_prep(sfdata, as.formula(design), target_mapping = t2g, extra_bootstrap_summary = TRUE) %>% 
        sleuth_fit()`

reading in kallisto results
dropping unused factor levels
.................................
normalizing est_counts
90630 targets passed the filter
normalizing tpm
merging in metadata
summarizing bootstraps ###I know the bootstraps are being read, just not sure what happens afterwards
.................................
fitting measurement error models
shrinkage estimation
computing variance of betas
Warning messages:
1: In check_num_cores(num_cores) :
  It appears that you are running Sleuth from within Rstudio.
Because of concerns with forking processes from a GUI, 'num_cores' is being set to 1.
If you wish to take advantage of multiple cores, please consider running sleuth from the command line.
2: In check_target_mapping(tmp_names, target_mapping) :
  intersection between target_id from kallisto runs and the target_mapping is empty. attempted to fix problem by removing .N from target_id, then merging back into target_mapping. please check obj$target_mapping to ensure this new mapping is correct.

`so`
	sleuth object

bears: 33 
design: ~condition + day

**Comment by rob-p** [comment]
Out of curiosity; do you see them present if you inspect the tables in the Shiny app (like the screenshot I shared above)?  Do they just disappear when you export the table, or do you not see them at all in the table explorer?

**Comment by rbenel** [comment]
I do not see them at all in the table explorer...

**Comment by rob-p** [comment]
Hi @rbenel,

  I've created a minimum working example (MWE) that you can grab from [here](https://drive.google.com/open?id=1xyru3S1Zu7gWNLmzZZTFbY_5zEkt2M83).  This is just a tarball with a directory containing the h5 files you provided above, along with a simple tsv file sample table and a tiny R script to load the data.  Can you download this and run (source) `LoadSampleData.R` to see if it works for you?  You should first set your working directory to the unzipped directory you get from this file.  I'm also attaching below my `session_info` in case that is useful.

```
> devtools::session_info()
Session info ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, darwin16.1.0        
 ui       RStudio (1.0.153)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       <NA>                        
 date     2018-06-13                  

Packages --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package       * version date       source                            
 assertthat      0.2.0   2017-04-11 CRAN (R 3.3.2)                    
 base          * 3.3.2   2016-11-01 local                             
 bindr           0.1.1   2018-03-13 CRAN (R 3.3.2)                    
 bindrcpp      * 0.2.2   2018-03-29 CRAN (R 3.3.2)                    
 BiocInstaller * 1.22.3  2016-08-05 Bioconductor                      
 colorspace      1.3-2   2016-12-14 CRAN (R 3.3.2)                    
 curl            3.2     2018-03-28 CRAN (R 3.3.2)                    
 data.table      1.11.4  2018-05-27 cran (@1.11.4)                    
 datasets      * 3.3.2   2016-11-01 local                             
 devtools        1.13.5  2018-02-18 CRAN (R 3.3.2)                    
 digest          0.6.15  2018-01-28 CRAN (R 3.3.2)                    
 dplyr         * 0.7.5   2018-05-19 CRAN (R 3.3.2)                    
 ggplot2         2.2.1   2016-12-30 CRAN (R 3.3.2)                    
 git2r           0.21.0  2018-01-04 CRAN (R 3.3.2)                    
 glue            1.2.0   2017-10-29 CRAN (R 3.3.2)                    
 graphics      * 3.3.2   2016-11-01 local                             
 grDevices     * 3.3.2   2016-11-01 local                             
 grid            3.3.2   2016-11-01 local                             
 gtable          0.2.0   2016-02-26 CRAN (R 3.3.1)                    
 htmltools       0.3.6   2017-04-28 CRAN (R 3.3.2)                    
 httpuv          1.4.3   2018-05-10 CRAN (R 3.3.2)                    
 httr            1.3.1   2017-08-20 CRAN (R 3.3.2)                    
 jsonlite        1.5     2017-06-01 CRAN (R 3.3.2)                    
 knitr           1.20    2018-02-20 CRAN (R 3.3.2)                    
 labeling        0.3     2014-08-23 CRAN (R 3.3.1)                    
 later           0.7.3   2018-06-08 CRAN (R 3.3.2)                    
 lazyeval        0.2.1   2017-10-29 CRAN (R 3.3.2)                    
 magrittr        1.5     2014-11-22 CRAN (R 3.3.1)                    
 matrixStats     0.53.1  2018-02-11 cran (@0.53.1)                    
 memoise         1.1.0   2017-04-21 CRAN (R 3.3.2)                    
 methods       * 3.3.2   2016-11-01 local                             
 mime            0.5     2016-07-07 CRAN (R 3.3.1)                    
 munsell         0.5.0   2018-06-12 CRAN (R 3.3.2)                    
 parallel        3.3.2   2016-11-01 local                             
 pillar          1.2.3   2018-05-25 CRAN (R 3.3.2)                    
 pkgconfig       2.0.1   2017-03-21 CRAN (R 3.3.2)                    
 plyr            1.8.4   2016-06-08 CRAN (R 3.3.1)                    
 promises        1.0.1   2018-04-13 CRAN (R 3.3.2)                    
 purrr           0.2.5   2018-05-29 CRAN (R 3.3.2)                    
 R6              2.2.2   2017-06-17 CRAN (R 3.3.2)                    
 Rcpp            0.12.17 2018-05-18 CRAN (R 3.3.2)                    
 reshape2        1.4.3   2017-12-11 CRAN (R 3.3.2)                    
 rhdf5           2.16.0  2017-02-23 cran (@2.16.0)                    
 rlang           0.2.1   2018-05-30 CRAN (R 3.3.2)                    
 scales          0.5.0   2017-08-24 CRAN (R 3.3.2)                    
 shiny         * 1.1.0   2018-05-17 CRAN (R 3.3.2)                    
 sleuth        * 0.30.0  2018-06-13 Github (pachterlab/sleuth@8bb7aa0)
 stats         * 3.3.2   2016-11-01 local                             
 stringi         1.2.3   2018-06-12 CRAN (R 3.3.2)                    
 stringr         1.3.1   2018-05-10 CRAN (R 3.3.2)                    
 tibble          1.4.2   2018-01-22 CRAN (R 3.3.2)                    
 tidyr           0.8.1   2018-05-18 CRAN (R 3.3.2)                    
 tidyselect      0.2.4   2018-02-26 CRAN (R 3.3.2)                    
 tools           3.3.2   2016-11-01 local                             
 utils         * 3.3.2   2016-11-01 local                             
 withr           2.1.2   2018-03-15 CRAN (R 3.3.2)                    
 xtable          1.8-2   2016-02-05 CRAN (R 3.3.1)                    
 zlibbioc        1.18.0  2016-08-05 Bioconductor          
```

**Comment by rbenel** [comment]
Hi @rob-p,
I still do not see the bootstraps, (see image below). Is it possible that something is causing it to be hidden? Or is it a version issue, because I see I am using R 3.4.4?
![cropped_sleuth](https://user-images.githubusercontent.com/39304679/41393631-5ce9d38c-6faf-11e8-955a-0a4c24afb7f3.png)

`session_info`

```
> devtools::session_info()
Session info -------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 system   x86_64, linux-gnu           
 ui       RStudio (1.1.453)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Asia/Jerusalem              
 date     2018-06-14                  

Packages -----------------------------------------------------------------------------------------------------
 package     * version date       source                            
 assertthat    0.2.0   2017-04-11 CRAN (R 3.4.4)                    
 base        * 3.4.4   2018-04-21 local                             
 bindr         0.1.1   2018-03-13 CRAN (R 3.4.4)                    
 bindrcpp    * 0.2.2   2018-03-29 CRAN (R 3.4.4)                    
 colorspace    1.3-2   2016-12-14 CRAN (R 3.4.4)                    
 compiler      3.4.4   2018-04-21 local                             
 data.table    1.11.2  2018-05-08 CRAN (R 3.4.4)                    
 datasets    * 3.4.4   2018-04-21 local                             
 devtools      1.13.5  2018-02-18 CRAN (R 3.4.4)                    
 digest        0.6.15  2018-01-28 CRAN (R 3.4.4)                    
 dplyr       * 0.7.5   2018-05-19 CRAN (R 3.4.4)                    
 ggplot2     * 2.2.1   2016-12-30 CRAN (R 3.4.4)                    
 glue          1.2.0   2017-10-29 CRAN (R 3.4.4)                    
 graphics    * 3.4.4   2018-04-21 local                             
 grDevices   * 3.4.4   2018-04-21 local                             
 grid          3.4.4   2018-04-21 local                             
 gtable        0.2.0   2016-02-26 CRAN (R 3.4.4)                    
 htmltools     0.3.6   2017-04-28 CRAN (R 3.4.4)                    
 httpuv        1.4.3   2018-05-10 CRAN (R 3.4.4)                    
 jsonlite      1.5     2017-06-01 CRAN (R 3.4.4)                    
 labeling      0.3     2014-08-23 CRAN (R 3.4.4)                    
 later         0.7.2   2018-05-01 CRAN (R 3.4.4)                    
 lazyeval      0.2.1   2017-10-29 CRAN (R 3.4.4)                    
 magrittr      1.5     2014-11-22 CRAN (R 3.4.4)                    
 matrixStats   0.53.1  2018-02-11 CRAN (R 3.4.4)                    
 memoise       1.1.0   2017-04-21 CRAN (R 3.4.4)                    
 methods     * 3.4.4   2018-04-21 local                             
 mime          0.5     2016-07-07 CRAN (R 3.4.4)                    
 munsell       0.4.3   2016-02-13 CRAN (R 3.4.4)                    
 parallel      3.4.4   2018-04-21 local                             
 pillar        1.2.2   2018-04-26 CRAN (R 3.4.4)                    
 pkgconfig     2.0.1   2017-03-21 CRAN (R 3.4.4)                    
 plyr          1.8.4   2016-06-08 CRAN (R 3.4.4)                    
 promises      1.0.1   2018-04-13 CRAN (R 3.4.4)                    
 purrr         0.2.4   2017-10-18 CRAN (R 3.4.4)                    
 R6            2.2.2   2017-06-17 CRAN (R 3.4.4)                    
 Rcpp          0.12.17 2018-05-18 CRAN (R 3.4.4)                    
 reshape2      1.4.3   2017-12-11 CRAN (R 3.4.4)                    
 rhdf5         2.22.0  2018-05-22 Bioconductor                      
 rlang         0.2.0   2018-02-20 CRAN (R 3.4.4)                    
 scales        0.5.0   2017-08-24 CRAN (R 3.4.4)                    
 shiny       * 1.1.0   2018-05-17 CRAN (R 3.4.4)                    
 sleuth      * 0.29.0  2018-05-22 Github (pachterlab/sleuth@8308dfd)
 stats       * 3.4.4   2018-04-21 local                             
 stringi       1.2.2   2018-05-02 CRAN (R 3.4.4)                    
 stringr       1.3.1   2018-05-10 CRAN (R 3.4.4)                    
 tibble        1.4.2   2018-01-22 CRAN (R 3.4.4)                    
 tidyr         0.8.1   2018-05-18 CRAN (R 3.4.4)                    
 tidyselect    0.2.4   2018-02-26 CRAN (R 3.4.4)                    
 tools         3.4.4   2018-04-21 local                             
 utils       * 3.4.4   2018-04-21 local                             
 withr         2.1.2   2018-03-15 CRAN (R 3.4.4)                    
 xtable        1.8-2   2016-02-05 CRAN (R 3.4.4)                    
 yaml          2.1.19  2018-05-01 CRAN (R 3.4.4)                    
 zlibbioc      1.24.0  2018-05-21 Bioconductor`

**Comment by rob-p** [comment]
This is even stranger.  I moved to R 3.4.4 just to see if it was a version issue.  However, I still see the bootstraps loaded properly:

<img width="2079" alt="image" src="https://user-images.githubusercontent.com/361470/41416203-4e879186-6fb8-11e8-984b-8dd9cf8c8503.png">


Here is my `sessionInfo`:

```
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.1

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.1.0          bindrcpp_0.2.2       dplyr_0.7.5          sleuth_0.30.0        BiocInstaller_1.28.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.17       later_0.7.3        pillar_1.2.3       compiler_3.4.4     git2r_0.21.0       plyr_1.8.4         bindr_0.1.1        tools_3.4.4        zlibbioc_1.24.0    digest_0.6.15     
[11] jsonlite_1.5       memoise_1.1.0      tibble_1.4.2       gtable_0.2.0       rhdf5_2.22.0       pkgconfig_2.0.1    rlang_0.2.1        curl_3.2           parallel_3.4.4     withr_2.1.2       
[21] httr_1.3.1         stringr_1.3.1      devtools_1.13.5    grid_3.4.4         tidyselect_0.2.4   glue_1.2.0         data.table_1.11.4  R6_2.2.2           ggplot2_2.2.1      purrr_0.2.5       
[31] tidyr_0.8.1        reshape2_1.4.3     magrittr_1.5       promises_1.0.1     htmltools_0.3.6    scales_0.5.0       matrixStats_0.53.1 assertthat_0.2.0   xtable_1.8-2       mime_0.5          
[41] colorspace_1.3-2   httpuv_1.4.3       stringi_1.2.3      lazyeval_0.2.1     munsell_0.5.0
```

The main differences of note, I think, are that I am running on OSX here instead of linux.  I am under RStudio (not sure if you are), and I have a sleuth version listed as `sleuth_0.30.0`.

**Comment by rbenel** [comment]
Hi @rob-p, 
I can try to update my sleuth package, that is more solvable than switching operating systems.. 
Re the bootstraps - do you think sleuth is reading them, and just not displaying the info? Or is it not processing that information at all? 
As always, thanks!

**Comment by rbenel** [comment]
Hi @rob-p, 
It seems it was a version issue. I am now using `sleuth 0.30.0` and I now have 100 bootstraps! 

Thank you so much for all of your help and patience! 

![screenshot from 2018-06-17 13-56-50](https://user-images.githubusercontent.com/39304679/41507195-59c3f7c6-7236-11e8-80d2-8ec945531fa8.png)

**Comment by rob-p** [comment]
Hi @rbenel ,

  Fantastic; I'm glad to see you were able to figure it out!  I'm sorry the solution ended up being so cryptic.

**Comment by rbenel** [comment]
Yes, who would have thought the difference was in the version number... 
Thank you again! 
Best, 
Rina

**Comment by rob-p** [comment]
You're quite welcome!

Best,
Rob
