### ISSUE TITLE
.Error during wrapup: File h5 has no bootstraps.Please generate bootstraps using "kallisto quant 

### ISSUE THREAD

**Issue by antonkulaga** [COMBINE-lab/wasabi#12]
I am getting bootstrap problems with files created by wasabi
```
 so <- sleuth_prep(s2c, extra_bootstrap_summary = FALSE)
reading in kallisto results
dropping unused factor levels
..
normalizing est_counts
42799 targets passed the filter
normalizing tpm
merging in metadata
summarizing bootstraps
.Error during wrapup: File h5 has no bootstraps.Please generate bootstraps using "kallisto quant -b".File /home/rstudio/samples/GSM1944768/transcripts_quant/abundance.h5 has no bootstraps.Please generate bootstraps using "kallisto quant -b".
```

**Comment by rob-p** [comment]
Can you share the source quant data, R version, and OS details? I can try to take a look.

**Comment by antonkulaga** [comment]
@rob-p I am checking if it is not my fault,  rerunning the quants with --numBootstraps 10
Anyway, it will be nice to put a warning to wassabi if bootstraps were not created. 
Also, I do not fully understand why you could not directly generate h5 in salmon and decided to write wasabi instead.

**Comment by rob-p** [comment]
Hi @antonkulaga,

  Sure --- let me know if it runs.  Generally, I believe that sleuth _requires_ bootstraps, so I agree that it would make sense to have a wasabi warning if none are present.

  The motivation for the decision to not generate the hdf5 directly in salmon is twofold.  First, salmon already has a large number of dependencies (which I have been slowly picking off and trying to reduce / simplify).  Static linking against the hdf5 library can be notoriously finicky, and I wanted to avoid having to deal with that on all of the platforms where we build salmon.  The other reason is that, downstream of quantification, this hdf5 format is currently _only_ used by sleuth (setting aside the quickly changing landscape of scRNA-seq quantification and projects like loompy).  Yet, there are a number of methods that try to account for quantification uncertainty, and we anticipate that there will likely be many more that gain this capability in the future.  Therefore, we prefer to save the relevant information in a simple format that can be parsed without relying on e.g. the hdf5 library to potentially simplify future integration with other tools.

**Comment by antonkulaga** [comment]
@rob-p looks like it was my problem (forgot to put number of bootstraps in parameters), however, even after I have another problem: sleuth does not want to open the generated files: https://github.com/COMBINE-lab/wasabi/issues/13
