### ISSUE TITLE
 #001: H5Gint.c line 833 in H5G_iterate(): unable to register group

### ISSUE THREAD

**Issue by antonkulaga** [COMBINE-lab/wasabi#13]
I have problems with sleuth reading files generated by wassabi. Here is the files with quantifications:
http://agingkills.westeurope.cloudapp.azure.com/pipelines/samples/GSE36041/

When I try to read them with:
```
install.packages('tidyverse', dependencies=TRUE, type="source")
library("sleuth")
library(tidyverse)
library(purrr)
library(stringr)
library(wasabi)

base <- file.path("/home", "rstudio", "samples")
samples <- c("GSM879796", "GSM879797")
quant <- "transcripts_quant"
pathes <- map_chr(samples, function(s) str_c(base, "/", s, "/", quant))
prepare_fish_for_sleuth(pathes)

conditions <- c("one", "two")

s2c = data.frame(
sample = samples,
condition = conditions,
path = pathes,
stringsAsFactors=FALSE
)
so <- sleuth_prep(s2c)
```
I get the following errors:
```
Reading in kallisto results
dropping unused factor levels
.HDF5-DIAG: Error detected in HDF5 (1.8.19) thread 0:
  #000: H5L.c line 1181 in H5Literate(): link iteration failed
    major: Symbol table
    minor: Iteration failed
  #001: H5Gint.c line 833 in H5G_iterate(): unable to register group
    major: Object atom
    minor: Unable to register new atom
  #002: H5I.c line 880 in H5I_register(): invalid type
    major: Object atom
    minor: Unable to find ID group information
Error: C stack usage  7971316 is too close to the limit
In addition: Warning message:
In check_num_cores(num_cores) :
  It appears that you are running Sleuth from within Rstudio.
Because of concerns with forking processes from a GUI, 'num_cores' is being set to 1.
If you wish to take advantage of multiple cores, please consider running sleuth from the command line.
```
The quantification was produced by the following: 
```
salmon --no-version-check quant -i /cromwell-executions/quantification/45484fec\
-09e3-4eea-aa0f-dd756250d9e2/call-salmon_novel/shard-2/inputs/1596470581/salmon\
  --numBootstraps 10 --threads 2 -l A --seqBias --gcBias --validateMappings --r\
angeFactorizationBins 4 -o transcripts_quant
```
Latest versions of evderything (sleuth, wassabi, salmon, bioconductor) were used.

**Comment by rob-p** [comment]
It [appears to be an rhdf5-related issue](https://github.com/grimbough/rhdf5/issues/6).

**Comment by antonkulaga** [comment]
@rob-p so, what is the potential work-around (other than switching to kallisto)? I currently get this error for all GSM-s I try. (problems with 5 GSE-s already)

**Comment by rob-p** [comment]
Hi @antonkulaga --- Regarding the hdf5 issue --- it's not clear to me that the problem is with either of these packages. The link I pointed to suggests that it's the R bindings to the hdf5 library itself; they changed the functionality of one of the functions. Can you pull down my latest commit to wasabi and try again? I replaced the calls to H5Close() with h5closeAll() which should restore the prior functionality.

**Comment by antonkulaga** [comment]
@rob-p thank you very much, with latest commit rhdf5 issue seems to be fixed.
However, now I am facing another issue, please, take a look https://github.com/COMBINE-lab/wasabi/issues/14
