### ISSUE TITLE
Tag releases?

### ISSUE THREAD

**Issue by dpryan79** [COMBINE-lab/wasabi#15]
Could you tag the releases? I'm currently updating wasabi in bioconda and having tagged releases makes things a bit clearer :)

**Comment by rob-p** [comment]
Hi Devon,

  I've tagged the current head of master at v1.0.0 to make integration easier.  Let me know if you need anything else.  Thanks for updating this in bioconda :)!

**Comment by dpryan79** [comment]
Thanks Rob!
