### ISSUE TITLE
Salmon aux copy error windows

### ISSUE THREAD

**Issue by royfrancis** [COMBINE-lab/wasabi#3]
Using this with some salmon files for import into sleuth.
I get this error:

```
Error in setnames(quant, c("target_id", "length", "tpm", "est_counts")) : 
  Can't assign 4 names to a 5 column data.table
```

My data file (quant.sf) looks like this

```
Name    Length  EffectiveLength TPM NumReads
ENSDART00000171117.1    11  11  0   0
ENSDART00000162914.1    10  10  0   0
ENSDART00000172037.1    344 169.752 4.10497 9
...
```

And I can't get to help
`?prepare_fish_for_sleuth`

**Comment by rob-p** [comment]
Hi @royfrancis, this looks like it's because wasabi's auto-determination of input file type is wrong here (i.e. it's interpreting this as an "old format" salmon file with only 4 columns, while you are using a "new format" salmon file with 5 columns).  Can you ensure that you're using the most recent version of Wasabi?  If so, might you provide a quantification directory so I can try and reproduce (and fix) this issue?

**Comment by royfrancis** [comment]
I installed wasabi like so:
`devtools::install_github("COMBINE-LAB/wasabi",force=T)`

My sessionInfo() shows `wasabi_0.1`.

**Comment by royfrancis** [comment]
Here are 4 directories of salmon results.
https://dl.dropboxusercontent.com/u/78814791/sites/salmon/salmon.zip

**Comment by rob-p** [comment]
Great; I'll take a look now.

**Comment by rob-p** [comment]
Hi Roy,

  The issue seems to be that, though you're using a recent version of salmon, the directories you sent don't seem to contain the `aux` subdirectory.  This subdirectory is present in newer versions of salmon (and sailfish) output, and wasabi checks for this to determine how it should interpret the quantification files.  Do you have any idea why the `aux` directory might be missing from these samples?

--Rob

**Comment by royfrancis** [comment]
Ummm.. I am not sure what an aux directory is. This is the output I get from Salmon. I don't think I have modified the output in any way.

To clarify, I use salmon like this

```
salmon quant \
-i "transcriptome-index" \
-o "$newfilename-salmon-quant" \
-l "ISR" \
-p 8 \
-1 <(zcat $1) \
-2 <(zcat $2)
```

I use SalmonBeta-0.6.1. It also says its a DebianSqueeze if that means anything.

**Comment by royfrancis** [comment]
Ah! The aux directories were accidentally not copied when downloading the files from the server to local.

**Comment by rob-p** [comment]
Hrmm; then it seems something is not being written as expected.  The way you're running `salmon` seems fine, but the output should look something like this:

```
├── aux
│   ├── expected_bias.gz
│   ├── observed_bias.gz
│   ├── fld.gz
│   └── meta_info.json
├── cmd_info.json
├── libFormatCounts.txt
├── libParams
│   └── flenDist.txt
├── logs
│   └── salmon_quant.log
└── quant.sf
```

The `aux` subdirectory of the quantification directory is where `salmon` stores metainformation about the run, and where `wasabi` looks to determine which input routine it should use.  Salmon should complain and exit if it is unable to create this directory, unless something very strange is happening in the underlying filesystem.

**Comment by rob-p** [comment]
Ok; just read your previous message.  Thank goodness, b/c it would be very difficult to debug why the `aux` directory wasn't being created!

**Comment by royfrancis** [comment]
Sorry about that! I didn't see that you have commented underneath. I just noticed it when refreshing the page.

**Comment by rob-p** [comment]
No problem.  Please let me know if including the `aux` directories fixes the problem.

**Comment by royfrancis** [comment]
I had problems to copy this directory from my linux server to windows computer. It also couldn't be created. Once I managed to copy it, there were many errors and warnings and then I couldn't delete it. I changed all permissions and worked as admin and it still didn't work. 

Eventually I came upon links like [this](https://blog.onetechnical.com/2006/11/16/forbidden-file-and-folder-names-on-windows/) that suggests `aux` is a forbidden directory name on windows which finally explains all the weirdness I've had. This whole thing was probably due to windows being stupid. I think I will just use kallisto to begin with.

**Comment by rob-p** [comment]
Hi @royfrancis,

  I didn't know you were trying to copy onto windows!  Yes, the `aux` naming scheme is a very arbitrary (and stupid) windows restriction.  I've had a user run into this before (this exact issue, using wasabi + sleuth on Windows), and this is why Salmon exposes the `--auxDir' option.  This option sets "The sub-directory of the quantification directory where auxiliary information e.g. bootstraps, bias parameters, etc. will be written."  Wasabi will respect this alternative directory, and you can use a different name that will work on Windows.  I'd suggest you give it a try (you could, for example, just re-run one sample to make sure it works for you).

--Rob
