### ISSUE TITLE
readBin reads half the expected number of bootstraps

### ISSUE THREAD

**Issue by DarwinAwardWinner** [COMBINE-lab/wasabi#4]
I'm trying to use wasabi, and I'm getting an error:

```
> fish_to_hdf5("salmon_quant/hg38.analysisSet_knownGene/SRR2454050", force=TRUE, -1)
Error in dim(boots) <- c(minfo$num_targets, minfo$num_bootstraps) : 
  dims [product 18260800] do not match the length of object [9130400]
```

It seems that exactly half the expected number of bootstraps are being read from the file. I verified that manually running the `gzcon` and `readBin` lines from `fish_to_hdf5` produces the same result. The actual number of transcripts and bootstraps in this sample are 182608 and 100, respectively. I've made the sample available via my Dropbox here: https://www.dropbox.com/sh/9prj2h4cct0ogv9/AADkn-_xk_F-qgY4mmX4mrtva?dl=0

**Comment by DarwinAwardWinner** [comment]
An additional note: The [ConvertBootstrapsToTSV.py](https://github.com/COMBINE-lab/salmon/blob/master/scripts/ConvertBootstrapsToTSV.py) script produces a tsv file with the correct number of bootstraps for this sample. (After fixing the script to use the correct aux dir)

**Comment by DarwinAwardWinner** [comment]
And reading that python script, I see:

``` python
    if meta_info['samp_type'] == 'gibbs':
        s = struct.Struct('<' + 'i' * ntxp)
    elif meta_info['samp_type'] == 'bootstrap':
        s = struct.Struct('@' + 'd' * ntxp)
```

for which the wasabi R code has no equivalent. I did indeed use Gibbs sampling, so this is clearly the cause of the problem.

**Comment by rob-p** [comment]
Indeed, the current version of wasabi was only written accounting for bootstrap estimates (not Gibbs).  It's trivial to make the appropriate modifications but I just hadn't gotten around to it yet.  I can take a look at this soon.

**Comment by DarwinAwardWinner** [comment]
Indeed, changing "double" to "integer" in the R code made the code run without errors. Is there any other adjustment I would need to do besides that?

**Comment by rob-p** [comment]
The only thing to make sure of is that when the results are written to the hdf5 file, they are written as doubles, since that is the datatype expected there.

The "generic" change to make (just as in the `ConvertBootstrapsToTSV.py` script) is to set the datatype based on the value of `samp_type`.

**Comment by DarwinAwardWinner** [comment]
How does this look? 

``` R
    if (numBoot > 0) {
        bootCon <- gzcon(file(file.path(auxPath, "bootstrap",
                                        "bootstraps.gz"), "rb"))
        dtype <- switch(minfo$samp_type, gibbs="integer", bootstrap="double",
                        stop(sprintf("Unknown sample type: %s", deparse(minfo$samp_type))))
        boots <- readBin(bootCon, dtype, n = minfo$num_targets *
                                             minfo$num_bootstraps)

        close(bootCon)
        boots <- as.numeric(boots)
        dim(boots) <- c(minfo$num_targets, minfo$num_bootstraps)
    }

```

**Comment by rob-p** [comment]
This seems perfectly cromulent.

**Comment by rob-p** [comment]
So, since salmon 0.7.3 (current dev version) and forward also output doubles for gibbs as well as bootstrap samples, I think I'll need to special case based on the versions a bit here.

**Comment by DarwinAwardWinner** [comment]
You could always take the duck typing approach of "try reading doubles, then fall back to reading int if that fails".

**Comment by rob-p** [comment]
Is there an idiomatic way to do that in R?  I'm still trying to improve my R-fu and wasabi is my first real R "package".

**Comment by DarwinAwardWinner** [comment]
Something like `tryCatch( [code for reading doubles] , error=function(...) { [code for reading ints] })`. 

(Although if you're reading from a file you might have to walk back to where you started reading if the first read fails. I forget if the HDF5 reading works like that.)

**Comment by DarwinAwardWinner** [comment]
Just make sure you first try the one that fails if it's wrong. Which I think is reading doubles, because they're bigger and you'll hit the end of the list of ints if you try to read doubles.

**Comment by rob-p** [comment]
Ok, I've implemented this strategy in the latest commit.  I still need to test it on some (older) integer-based Gibbs sampling runs.

**Comment by rob-p** [comment]
Ok --- This fix is in place (and tested) now.  It should work, so I'm going to close this issue.
