### ISSUE TITLE
Salmon 0.7.2 defaults to aux_info not recognised by wasabi

### ISSUE THREAD

**Issue by sschmeier** [COMBINE-lab/wasabi#5]
Hi,
Probably known to you. 
I tried to use salmon output with wasabi. I used the bioconda version. 
Salmon 0.7.2
Wasabi 0.01, well at least thats what the conda version says, however looking at the yml file it seems, the latest wasabi will be installed in any case? (needs and update at bioconda?)

However, the actual problem, is that salmon creates "aux_info" directories by default. 
When calling wasabi method:

> prepare_fish_for_sleuth(sf_dirs)
> Error in setnames(quant, c("target_id", "length", "tpm", "est_counts")) :
>   Can't assign 4 names to a 5 column data.table

When renaming salmon output dir "aux_info" to "aux", it works. So its probably not a bug but one has to be aware that salmon defaults to aux_info and not aux... 

Cheers,
    Seb

**Comment by rob-p** [comment]
Hi Seb,

  Thanks for reporting this.  I actually think this is OK in master, it's just that the bioconda package needs to be updated.  After I incorporate [Ryan's enhancement](https://github.com/COMBINE-lab/wasabi/issues/4), I'll bump the version and submit a PR to bioconda.

Thanks,
Rob

**Comment by rob-p** [comment]
This should be fixed now --- I'll bump the version and ask bioconda to update.
